### ISSUE TITLE
[FEATURE] Build SI Documentation Website

### ISSUE THREAD

**Issue by alexlovelltroy** [OpenCHAMI/roadmap#9]
**Documentation Quality Matters**
Our interns will use OpenCHAMI to manage their clusters starting in June.  We need documentation they can follow to set up the microservices and/or the VM.  Some of them will be working on OpenCHAMI directly.   Others will be working with OpenCHAMI as their cluster manager for other kinds of projects.

**Describe the solution you'd like**
I'd like to see a documentation website for basic information about how OpenCHAMI works with links to a git repository they can fork to set up their own cluster.

**Comment by synackd** [comment]
How much of this should be included in the student guide and how much in a separate site?

I imagine having a walkthrough with basic usage could be in the guide and a link to an Ochami-specific documentation site could be included.

**Comment by alexlovelltroy** [comment]
https://si.lisdi-pages.lanl.gov/si-guide-admin/ exists!  We can close this and other issues will refine what the contents of the admin guide should be.  At this point, this is not accessible outside LANL.
